### PR TITLE
fix: avro parser now handles record reuse in definitions

### LINKED ISSUE #111: Avro parser does not store sub definitions
#### Describe the bug
When parsing an Avro document the parser does not store the seen record definitions leading to not found errors in valid schemas. 

#### How to Reproduce

To reproduce just embed the following schema in a valid asyncAPI document and run it through the generator. 

```avro
{
  "type": "record",
  "name": "ConnectionRequested",
  "namespace": "com.foo.connections",
  "doc": "An example schema to illustrate the issue",
  "fields": [
    {
      "name": "metadata",
      "type": {
        "type": "record",
        "name": "EventMetadata",
        "namespace": "com.foo",
        "doc": "Metadata to be associated with every published event",
        "fields": [
          {
            "name": "id",
            "type": {
              "type": "string",
              "logicalType": "uuid"
            },
            "doc": "Unique identifier for this specific event"
          },
          {
            "name": "timestamp",
            "type": {
              "type": "long",
              "logicalType": "timestamp-millis"
            },
            "doc": "Instant the event took place (not necessary when it was published)"
          },
          {
            "name": "correlation_id",
            "type": [
              "null",
              {
                "type": "string",
                "logicalType": "uuid"
              }
            ],
            "doc": "id of the event that resulted in this\nevent being published (optional)",
            "default": null
          },
          {
            "name": "publisher_context",
            "type": [
              "null",
              {
                "type": "map",
                "values": {
                  "type": "string",
                  "avro.java.string": "String"
                },
                "avro.java.string": "String"
              }
            ],
            "doc": "optional set of key-value pairs of context to be echoed back\nin any resulting message (like a richer\ncorrelationId.\n\nThese values are likely only meaningful to the publisher\nof the correlated event",
            "default": null
          }
        ]
      }
    },
    {
      "name": "auth_code",
      "type": {
        "type": "record",
        "name": "EncryptedString",
        "namespace": "com.foo",
        "doc": "A string that was encrypted with AES (using CTR mode), its key encrypted with RSA, and the nonce used for the encryption.",
        "fields": [
          {
            "name": "value",
            "type": "bytes",
            "doc": "A sequence of bytes that has been AES encrypted in CTR mode."
          },
          {
            "name": "nonce",
            "type": "bytes",
            "doc": "A nonce, used by the CTR encryption mode for our encrypted value. Not encrypted, not a secret."
          },
          {
            "name": "key",
            "type": "bytes",
            "doc": "An AES key, used to encrypt the value field, that has itself been encrypted using RSA."
          }
        ]
      },
      "doc": "Encrypted auth_code received when user authorizes the app."
    },
    {
      "name": "refresh_token",
      "type": "com.foo.EncryptedString",
      "doc": "Encrypted refresh_token generated by using clientId and clientSecret."
    },
    {
      "name": "triggered_by",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      },
      "doc": "ID of the user who triggered this event."
    }
  ]
}
```

Running the following through the parser will result in: 

```
Something went wrong:
Error: undefined type name: com.foo.EncryptedString
    at parse (/Users/jkolb/.nvm/versions/node/v12.16.2/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/lib/parser.js:112:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

#### Expected behavior
The above schema should parse just fine as `com.foo.EncryptedString` was defined earlier in the schema which is valid Avro.

### LINKED ISSUE #113: Missing visualization of Avro schema with reference
#### Describe the bug
I am using an asyncapi with a reference on a `.avsc` file. The avro schema itself contains a reference on a `address` schema. The reference itself is not properly visualized (`streetaddress` and `city` missing).

asyncapi-avro-ref-issue

#### How to Reproduce
The shown example can be found here:
https://github.com/tstuber/asyncapi-avro-ref-issue

#### Expected behavior
I would expect that the `address` schema definition would be visualized properly as nested element in `person`.

### PR DESCRIPTION
**Pull request by kolb0401**
**Description**

- Adds a record cache by fully qualified name and uses the cache rather than trying to parse when the type matches the cached record.

**Related issue(s)**
Fixes #111 
Fixes #113

### CODE REVIEW

File: to-json-schema.js [hunk 1]
```diff
@@ -136,21 +136,39 @@ function validateAvroSchema(avroDefinition) {
...
+  if (key) {
+    cache[key] = value;
+  }
+}
+
+async function convertAvroToJsonSchema(avroDefinition, isTopLevel, recordCache = {}) {
   const jsonSchema = {};
   const isUnion = Array.isArray(avroDefinition);
 
-  validateAvroSchema(avroDefinition);
```
Comment (kolb0401) [inline to-json-schema.js:143]: This was moved outside the recursion because in the case of union Avro schemas the entire schema is valid but the sub pieces are not when the `n + 1` records contain a type defined in `n`

**Comment by kolb0401** [comment]
@derberg @fmvilas @M3lkior @dalelane Would love some feedback on this. It's currently blocking my companies ability to integrate this awesome tool.

**Review by fmvilas — APPROVED** [review]
Looks good to me 👍 Let's wait for the other code owners to review.

**Review by M3lkior — APPROVED** [review]
It seems ok for me ! Thanks for the contribution and welcome to the contributor family :)

**Comment by fmvilas** [comment]
@kolb0401 I would just create a follow-up issue but don't think it's important enough to block this fix.

**Comment by kolb0401** [comment]
@fmvilas Sounds good I can open that later. Anything further I need to do to get this merged?

**Comment by fmvilas** [comment]
Yeah, please raise the number of maximum warnings in https://github.com/asyncapi/avro-schema-parser/blob/master/package.json#L9. Just so CI doesn't fail for now. Make sure you create the follow-up issue before merging this one and leave a comment here.

Also, let's give some more time to the rest of the code owners to have a look 🙏

**Comment by M3lkior** [comment]
for the cognitive alert, you can maybe change the `eslint` rule waiting the related issue to be achieved ? what do you think about that @fmvilas ?

This can be done by updating the `.eslintrc.yaml` according [to this documentation](https://github.com/SonarSource/eslint-plugin-sonarjs/blob/master/docs/rules/cognitive-complexity.md)

**Review by dalelane — APPROVED** [review]
looks good, thanks!

**Comment by fmvilas** [comment]
> for the cognitive alert, you can maybe change the eslint rule waiting the related issue to be achieved ? what do you think about that @fmvilas ?

I would not do this because that would prevent us from getting future warnings in other parts of the code. IMHO, I think it's better to raise the number to accept just 1 warning (this one) and, if a new one appears in the future, we'll see CI fail again.

**Comment by M3lkior** [comment]
> > for the cognitive alert, you can maybe change the eslint rule waiting the related issue to be achieved ? what do you think about that @fmvilas ?
> 
> I would not do this because that would prevent us from getting future warnings in other parts of the code. IMHO, I think it's better to raise the number to accept just 1 warning (this one) and, if a new one appears in the future, we'll see CI fail again.

yes this is more suitable

**Comment by kolb0401** [comment]
https://github.com/asyncapi/avro-schema-parser/issues/114

The issue to reduce the cognitive complexity.

**Review by fmvilas — APPROVED** [review]

**Comment by kolb0401** [comment]
@fmvilas this will fix the lint issue once this PR is merged: https://github.com/asyncapi/avro-schema-parser/pull/115
